sudo: required
services:
  - docker

before_install:
  - docker build -t brungo1995/docker_react -f Dockerfile.dev .

# commands that need to be executed to run our test suite
script: 
  # Run tests and exit terminal otherwhise hangs there waiting for input
  - docker run -e CI=true brungo1995/docker_react npm run test
  # - docker run brungo1995/docker_react npm run test -- --coverage