sudo: required
services:
  - docker

before_install:
  - docker build -t brungo1995/docker-react -f Dockerfile.dev .

# commands that need to be executed to run our test suite
script: 
  # Run tests and exit terminal otherwhise hangs there waiting for input
  - docker run -e CI=true brungo1995/docker-react npm run test

  # if you set up elastic beanstalk with AWS add this set up below
deploy:
  provider: elasticbeanstalk
  # choos the region where deployed your elastic beanstal region
  region: af-south-1
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-af-south-1-046272106737"
  bucket_path: "docker-react"
  on:
  # Only trigger the build process when deployed to the master branch
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

# After all is successfull run this script to push to docker hub
# after_success:
#   - sh .travis/deploy_dockerhub.sh
#   – test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
